# Generated by Django 6.0.1 on 2026-01-16 22:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_question', models.TextField()),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTaxonomyProposal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('question', models.TextField()),
                ('feasibility_analysis', models.TextField()),
                ('proposed_fact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('proposed_logic', models.TextField(help_text='Pseudo-code or description of how to compute this fact')),
                ('proposed_schema', models.JSONField(blank=True, default=dict)),
                ('proposed_template', models.TextField(blank=True, null=True)),
                ('proposed_data_type', models.CharField(choices=[('scalar', 'Scalar'), ('dict', 'Dict'), ('list', 'List'), ('dataframe', 'Dataframe'), ('distribution', 'Distribution')], default='scalar', max_length=50)),
                ('proposed_requires', models.JSONField(default=list)),
                ('proposed_logic_type', models.CharField(choices=[('python', 'Python'), ('expression', 'Expression (SimpleEval)')], default='python', max_length=20)),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='List of {context, expected_type, expected_contains}')),
                ('approval_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='facts.factdefinitionversion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical taxonomy proposal',
                'verbose_name_plural': 'historical taxonomy proposals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxonomyProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('feasibility_analysis', models.TextField()),
                ('proposed_fact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('proposed_logic', models.TextField(help_text='Pseudo-code or description of how to compute this fact')),
                ('proposed_schema', models.JSONField(blank=True, default=dict)),
                ('proposed_template', models.TextField(blank=True, null=True)),
                ('proposed_data_type', models.CharField(choices=[('scalar', 'Scalar'), ('dict', 'Dict'), ('list', 'List'), ('dataframe', 'Dataframe'), ('distribution', 'Distribution')], default='scalar', max_length=50)),
                ('proposed_requires', models.JSONField(default=list)),
                ('proposed_logic_type', models.CharField(choices=[('python', 'Python'), ('expression', 'Expression (SimpleEval)')], default='python', max_length=20)),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='List of {context, expected_type, expected_contains}')),
                ('approval_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.factdefinitionversion')),
            ],
        ),
    ]
