# Generated by Django 6.0.1 on 2026-01-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyproposal',
            name='proposed_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxonomyproposal',
            name='proposed_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
