# Generated by Django 6.0.1 on 2026-01-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_taxonomyproposal_proposed_schema_and_more'),
        ('facts', '0004_refactor_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyproposal',
            name='created_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.factdefinitionversion'),
        ),
    ]
