# Generated by Django 4.2 on 2024-05-22 00:00

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactDefinition',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('namespace', models.CharField(blank=True, db_index=True, max_length=100)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('scalar', 'Scalar'), ('dict', 'Dict'), ('list', 'List'), ('dataframe', 'Dataframe'), ('distribution', 'Distribution')], default='scalar', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactDefinitionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('requires', models.JSONField(default=list)),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='Structured dependency edges')),
                ('parameters_schema', models.JSONField(blank=True, default=dict)),
                ('output_template', models.TextField(blank=True, null=True)),
                ('logic_type', models.CharField(choices=[('python', 'Python'), ('expression', 'Expression (SimpleEval)')], default='python', max_length=20)),
                ('code', models.TextField(help_text='Python code or DSL')),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='List of {context, expected} for validation')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fact_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='facts.factdefinition')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('fact_definition', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FactInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('context_hash', models.CharField(db_index=True, max_length=64)),
                ('value', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('provenance', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('confidence', models.FloatField(default=1.0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('fact_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='facts.factdefinitionversion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntentRecognizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_questions', models.JSONField(blank=True, default=list)),
                ('regex_patterns', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fact_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recognizer', to='facts.factdefinitionversion')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFactDefinitionVersion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('requires', models.JSONField(default=list)),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='Structured dependency edges')),
                ('parameters_schema', models.JSONField(blank=True, default=dict)),
                ('output_template', models.TextField(blank=True, null=True)),
                ('logic_type', models.CharField(choices=[('python', 'Python'), ('expression', 'Expression (SimpleEval)')], default='python', max_length=20)),
                ('code', models.TextField(help_text='Python code or DSL')),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='List of {context, expected} for validation')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('change_note', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fact_definition', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='facts.factdefinition')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fact definition version',
                'verbose_name_plural': 'historical fact definition versions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFactDefinition',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255)),
                ('namespace', models.CharField(blank=True, db_index=True, max_length=100)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('scalar', 'Scalar'), ('dict', 'Dict'), ('list', 'List'), ('dataframe', 'Dataframe'), ('distribution', 'Distribution')], default='scalar', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fact definition',
                'verbose_name_plural': 'historical fact definitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FactInstanceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_fact_id', models.CharField(max_length=255)),
                ('dependency_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='facts.factinstance')),
                ('parent_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='facts.factinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facts_used', models.ManyToManyField(blank=True, to='facts.factinstance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='facts.question')),
            ],
        ),
        migrations.AddIndex(
            model_name='factinstance',
            index=models.Index(fields=['fact_version', 'context_hash'], name='facts_facti_fact_ve_60814a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factinstance',
            unique_together={('fact_version', 'context_hash')},
        ),
    ]
