# Generated by Django 6.0.1 on 2026-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFact',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('kind', models.CharField(default='computed', max_length=50)),
                ('data_type', models.CharField(default='scalar', max_length=50)),
                ('requires', models.JSONField(default=list)),
                ('code', models.TextField(help_text='Python code defining the producer function. Must accept (deps, context).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
