# Generated by Django 4.2 on 2024-05-23 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.core.serializers.json

class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factdefinition',
            name='namespace',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factdefinition',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='factdefinitionversion',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, help_text='Structured dependency edges'),
        ),
        migrations.AddField(
            model_name='factinstance',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='factinstance',
            name='provenance',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='factinstance',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factinstance',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IntentRecognizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_questions', models.JSONField(blank=True, default=list)),
                ('regex_patterns', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fact_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recognizer', to='facts.factdefinitionversion')),
            ],
        ),
    ]
