# Generated by Django 6.0.1 on 2026-01-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_dynamicfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfact',
            name='output_template',
            field=models.TextField(blank=True, help_text='Jinja2-style template for the answer string', null=True),
        ),
        migrations.AddField(
            model_name='dynamicfact',
            name='parameters_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON Schema for context parameters'),
        ),
        migrations.AlterField(
            model_name='dynamicfact',
            name='code',
            field=models.TextField(help_text='Python code defining the producer function.'),
        ),
    ]
