# Generated by Manual Refactor

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import django.core.serializers.json

def migrate_dynamic_facts(apps, schema_editor):
    DynamicFact = apps.get_model('facts', 'DynamicFact')
    FactDefinition = apps.get_model('facts', 'FactDefinition')
    FactDefinitionVersion = apps.get_model('facts', 'FactDefinitionVersion')
    
    for df in DynamicFact.objects.all():
        # Create Definition
        defn, _ = FactDefinition.objects.get_or_create(
            id=df.id,
            defaults={
                'description': df.description,
                'data_type': df.data_type,
                'is_active': df.is_active
            }
        )
        
        # Create Version (v1)
        FactDefinitionVersion.objects.create(
            fact_definition=defn,
            version=1,
            requires=df.requires,
            parameters_schema=df.parameters_schema,
            output_template=df.output_template,
            code=df.code,
            status='approved' if df.is_active else 'deprecated',
            change_note="Migrated from DynamicFact"
        )

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facts', '0003_dynamicfact_output_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactDefinition',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(default='string', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactDefinitionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('requires', models.JSONField(default=list)),
                ('parameters_schema', models.JSONField(blank=True, default=dict)),
                ('output_template', models.TextField(blank=True, null=True)),
                ('code', models.TextField(help_text='Python code or DSL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fact_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='facts.factdefinition')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('fact_definition', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FactInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('context_hash', models.CharField(db_index=True, max_length=64)),
                ('value', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('fact_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='facts.factdefinitionversion')),
            ],
        ),
        migrations.CreateModel(
            name='FactInstanceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_fact_id', models.CharField(max_length=255)),
                ('dependency_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='facts.factinstance')),
                ('parent_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='facts.factinstance')),
            ],
        ),
        migrations.RunPython(migrate_dynamic_facts),
        migrations.RemoveField(
            model_name='answer',
            name='facts_used',
        ),
        migrations.AddField(
            model_name='answer',
            name='facts_used',
            field=models.ManyToManyField(blank=True, to='facts.factinstance'),
        ),
        migrations.DeleteModel(
            name='DynamicFact',
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
        migrations.DeleteModel(
            name='FactType',
        ),
        migrations.AddIndex(
            model_name='factinstance',
            index=models.Index(fields=['fact_version', 'context_hash'], name='facts_facti_fact_ve_idx'),
        ),
    ]
