# Generated by Django 6.0.1 on 2026-01-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_refactor_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='factdefinitionversion',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='List of {context, expected} for validation'),
        ),
    ]
