# Generated by Manual Migration

from django.db import migrations

ALL_TRANSACTIONS_CODE = """
user = context.get('user')
bank_qs = BankTransaction.objects.all()
cc_qs = CreditCardTransaction.objects.all()

if user:
    bank_qs = bank_qs.filter(account__user=user)
    cc_qs = cc_qs.filter(account__user=user)

bank_txs = list(bank_qs.values('posting_date', 'description', 'amount', 'type', 'account__name'))
for tx in bank_txs:
    tx['date'] = tx.pop('posting_date').isoformat()
    tx['category'] = 'Bank Transaction'
    tx['amount'] = float(tx['amount'])
    
cc_txs = list(cc_qs.values('transaction_date', 'description', 'amount', 'category', 'type', 'account__name'))
for tx in cc_txs:
    tx['date'] = tx.pop('transaction_date').isoformat()
    tx['amount'] = float(tx['amount'])

return bank_txs + cc_txs
"""

def insert_all_transactions(apps, schema_editor):
    FactDefinition = apps.get_model('facts', 'FactDefinition')
    FactDefinitionVersion = apps.get_model('facts', 'FactDefinitionVersion')
    
    defn, _ = FactDefinition.objects.get_or_create(
        id='all_transactions',
        defaults={
            'description': 'All transactions from database normalized',
            'data_type': 'list',
            'is_active': True
        }
    )
    
    FactDefinitionVersion.objects.create(
        fact_definition=defn,
        version=1,
        requires=[],
        code=ALL_TRANSACTIONS_CODE,
        status='approved',
        change_note="Initial migration of hardcoded logic"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_all_transactions),
    ]
