from django.db import models

class TaxonomyProposal(models.Model):
    """
    Stores proposals generated by the LLM for extending the fact taxonomy.
    """
    question = models.TextField()
    feasibility_analysis = models.TextField()
    proposed_fact_id = models.CharField(max_length=255, blank=True, null=True)
    proposed_logic = models.TextField(help_text="Pseudo-code or description of how to compute this fact")
    
    # NEW: Store proposed schema and template
    proposed_schema = models.JSONField(default=dict, blank=True)
    proposed_template = models.TextField(blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, default='pending', choices=[
        ('pending', 'Pending Review'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected')
    ])

    def __str__(self):
        return f"Proposal for: {self.question[:50]}..."

class CapabilitySuggestion(models.Model):
    suggested_question = models.TextField()
    reasoning = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.suggested_question
